project:
  type: website

website:
  title: "EPSRC Health Data Workshops"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: team.qmd
        text: Team

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

execute:
  freeze: auto
