project:
  type: website

website:
  title: "Health Data Science Research"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: team.qmd
        text: Team

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

execute:
  freeze: auto
